//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MbanqClients.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osobe
    {
        public int ID { get; set; }
        public int OIB { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Mjesto { get; set; }
        public string Adresa { get; set; }
        public int Telefon { get; set; }
        public string Mail { get; set; }
    }
}
